const $=id=>document.getElementById(id);
const ideas={
 coffee:{icon:"☕",title:"Кофе + прогулка",place:"уютная кофейня и прогулка без маршрута",message:"Хочу позвать тебя на кофе, а потом гулять столько, сколько захочется. Без спешки и сложного плана.",clue:"coffee",description:"Начать с любимого напитка, выбрать направление монеткой и найти одно новое место."},
 sunset:{icon:"🌇",title:"Закат с термосом",place:"место с красивым видом на закат",message:"Давай поймаем закат: я возьму что-нибудь тёплое, а ты — хорошее настроение.",clue:"city",description:"Тёплый напиток, плед и двадцать минут без телефонов, пока город меняет цвет."},
 museum:{icon:"🖼️",title:"Музейный квест",place:"музей или небольшая галерея",message:"Предлагаю выбрать самые странные работы в музее и придумать им новые названия. Победителю — десерт.",clue:"surprise",description:"Найти самую смешную, красивую и непонятную работу, а после обменяться открытиями."},
 picnic:{icon:"🧺",title:"Секретный пикник",place:"парк — точку пришлю после согласия",message:"Я соберу маленький пикник, а тебе нужно только выбрать любимый напиток и прийти.",clue:"surprise",description:"Три любимые закуски, уютная точка и один сюрприз, который пока останется тайной."},
 cinema:{icon:"🎬",title:"Кино наоборот",place:"кинотеатр и место с десертами",message:"Давай сначала выберем десерт, а уже по нему — фильм. Логика сомнительная, вечер обещает быть хорошим.",clue:"cinema",description:"Сначала десерт, затем спонтанный выбор фильма и честная рецензия по дороге домой."},
 night:{icon:"🔭",title:"Ночь и звёзды",place:"тихая набережная или планетарий",message:"Хочу вместе искать созвездия, даже если половину мы придумаем сами.",clue:"city",description:"Ночная прогулка, карта звёзд и право назвать одно новое созвездие в честь этого вечера."},
 food:{icon:"🥟",title:"Гастро-маршрут",place:"три небольших места в центре",message:"Предлагаю гастро-квест: по одному блюду в трёх местах и общий рейтинг в финале.",clue:"surprise",description:"Закуска, главное и десерт — каждое в новом месте. Следующую точку выбираете по очереди."},
 creative:{icon:"🎨",title:"Творческий вечер",place:"творческая студия",message:"Давай сделаем что-то руками и заберём домой смешной артефакт нашего вечера.",clue:"surprise",description:"Глина, краски или свечи: важен не результат, а вещь, которая останется после встречи."},
 active:{icon:"⛸️",title:"Активная авантюра",place:"каток, роллердром или боулинг",message:"Предлагаю немного движения, дружеское соревнование и обязательный напиток после.",clue:"surprise",description:"Выбрать активность по погоде, придумать несерьёзный приз и закончить вечер чем-нибудь тёплым."},
 book:{icon:"📚",title:"Книжное свидание",place:"большой книжный и кофейня рядом",message:"Давай выберем друг другу по книге — красивой, странной или очень точной.",clue:"coffee",description:"Тридцать минут на поиски книги друг для друга, затем кофе и объяснение своего выбора."},
 photo:{icon:"📷",title:"Фотоохота",place:"красивый район города",message:"У меня есть список из семи кадров. Давай соберём их за одну прогулку и сохраним этот вечер.",clue:"city",description:"Семь фото-улик: отражение, любимый цвет, смешная вывеска, общий кадр и три сюрприза."},
 custom:{icon:"✦",title:"Наша собственная история",place:"место — пока сюрприз",message:"У меня есть идея провести с тобой хороший вечер. Остальное соберём вместе.",clue:"surprise",description:"Свободный сценарий: только вы решаете, каким будет маршрут и что станет его главным моментом."}
};
const ideaTags={coffee:["уютно","романтично","без спешки","больше смеяться"],sunset:["романтично","уютно","загадочно","убрать телефоны"],museum:["необычно","загадочно","пробовать новое","больше смеяться"],picnic:["уютно","романтично","спонтанно","без спешки"],cinema:["уютно","весело","спонтанно","убрать телефоны"],night:["загадочно","романтично","необычно","сделать общее фото"],food:["весело","спонтанно","пробовать новое","больше смеяться"],creative:["необычно","уютно","пробовать новое","сделать общее фото"],active:["весело","спонтанно","пробовать новое","больше смеяться"],book:["уютно","загадочно","без спешки","убрать телефоны"],photo:["необычно","весело","спонтанно","сделать общее фото"],custom:["уютно","спонтанно","загадочно","романтично","весело","необычно"]};
const defaults={from:"Маша",to:"Саша",openingText:"у меня для тебя кое-что тёплое.",openingNote:"Никаких входов, камеры или оплаты. Только одна маленькая история.",theme:"tender",idea:"coffee",selectedIdeas:["coffee","sunset","museum"],message:ideas.coffee.message,place:ideas.coffee.place,date:"",dateFrom:"",dateTo:"",coverPhoto:"",clue:"coffee",replyChannel:"whatsapp",replyContact:""};
const allowed={theme:["tender","playful","mystery","bold","cozy","minimal"],idea:Object.keys(ideas),clue:["coffee","city","cinema","surprise"],replyChannel:["whatsapp","email","telegram"]};
const state={...defaults};let scene=0,feeling="уютно",token="без спешки",extra="ничего — план идеален",guestDate="";
const copy={tender:{intro:"у меня для тебя кое-что тёплое.",yes:"Мне очень приятно. Кажется, впереди хороший вечер ✦",mark:"♥"},playful:{intro:"кажется, намечается маленькая авантюра.",yes:"Вот это поворот. Приключение официально начинается ✦",mark:"✦"},mystery:{intro:"для тебя пришло послание из нашего будущего.",yes:"Будущее стало немного яснее. До встречи под звёздами ✦",mark:"☾"},bold:{intro:"отложи планы — у меня есть идея лучше.",yes:"Смелое предложение получило идеальный ответ ⚡",mark:"⚡"},cozy:{intro:"давай на вечер исчезнем от всей суеты.",yes:"Тёплый вечер уже стал чуть реальнее ☕",mark:"☕"},minimal:{intro:"есть одно предложение. Откроешь?",yes:"Договорились. Просто и прекрасно.",mark:"○"}};
const clueIcons={coffee:"☕",city:"✦",cinema:"◐",surprise:"?"};
function safeText(value,max,fallback=""){return typeof value==="string"?value.trim().slice(0,max)||fallback:fallback}
function normalize(raw={}){return{from:safeText(raw.from,40,defaults.from),to:safeText(raw.to,40,defaults.to),openingText:safeText(raw.openingText,120,copy?.[raw.theme]?.intro||defaults.openingText),openingNote:safeText(raw.openingNote,180,defaults.openingNote),theme:allowed.theme.includes(raw.theme)?raw.theme:defaults.theme,idea:allowed.idea.includes(raw.idea)?raw.idea:defaults.idea,selectedIdeas:Array.isArray(raw.selectedIdeas)?raw.selectedIdeas.filter(x=>allowed.idea.includes(x)).slice(0,6):defaults.selectedIdeas,message:safeText(raw.message,280,defaults.message),place:safeText(raw.place,80,defaults.place),date:/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(raw.date||"")?raw.date:"",dateFrom:/^\d{4}-\d{2}-\d{2}$/.test(raw.dateFrom||"")?raw.dateFrom:"",dateTo:/^\d{4}-\d{2}-\d{2}$/.test(raw.dateTo||"")?raw.dateTo:"",coverPhoto:typeof raw.coverPhoto==="string"&&raw.coverPhoto.startsWith("data:image/")&&raw.coverPhoto.length<180000?raw.coverPhoto:"",clue:allowed.clue.includes(raw.clue)?raw.clue:defaults.clue,replyChannel:allowed.replyChannel.includes(raw.replyChannel)?raw.replyChannel:defaults.replyChannel,replyContact:safeText(raw.replyContact,100,"")}}
function read(){["from","to","openingText","openingNote","message","place","date","dateFrom","dateTo","replyChannel","replyContact"].forEach(k=>state[k]=$(k).value);return Object.assign(state,normalize({...state,selectedIdeas:state.selectedIdeas}))}
function fmt(value){if(!value)return"время выберем вместе";const date=new Date(value);return Number.isNaN(date.valueOf())?"время уточним":new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"long",hour:"2-digit",minute:"2-digit"}).format(date)}
function contactHelp(){const map={whatsapp:"Получатель откроет ваш чат WhatsApp с готовым ответом и сам подтвердит отправку.",email:"Откроется новое письмо на указанный email с готовой темой и ответом.",telegram:"Укажите username без @. Telegram откроет ваш профиль; текст ответа будет заранее скопирован."};$("contactHelp").textContent=map[state.replyChannel];$("replyContact").placeholder=state.replyChannel==="email"?"name@example.com":state.replyChannel==="telegram"?"username":"+79990000000"}
function sync(){read();document.body.dataset.theme=state.theme;const idea=ideas[state.idea];$("introFrom").textContent=state.from;$("waxMark").textContent=copy[state.theme].mark;$("introTitle").textContent=(state.to||"Тебе")+", "+state.openingText;$("introNote").textContent=state.openingNote;$("letterTo").textContent=(state.to||"Тебе")+", это для тебя";$("letterText").textContent=state.message;$("placePill").textContent="⌖ "+state.place;$("datePill").textContent="◷ "+fmt(state.date);$("messageCount").textContent=$("message").value.length;$("replyTo").textContent=state.from;$("ideaTitle").textContent=idea.title;$("ideaIcon").textContent=idea.icon;$("ideaDescription").textContent=idea.description;$("coverPreview").src=state.coverPhoto||"";$("coverFallback").style.display=state.coverPhoto?"none":"block";$("guestDate").min=state.dateFrom?state.dateFrom+"T00:00":"";$("guestDate").max=state.dateTo?state.dateTo+"T23:59":"";contactHelp()}
function setScene(n){scene=Math.max(0,Math.min(8,n));document.querySelectorAll(".scene").forEach((el,i)=>{el.classList.toggle("active",i===scene);el.classList.toggle("exit",i<scene)});document.querySelectorAll(".progress i").forEach((el,i)=>el.classList.toggle("on",i<=Math.min(scene,6)));$("stepText").textContent=Math.min(scene+1,7)+" / 7"}
function encode(){read();const bytes=new TextEncoder().encode(JSON.stringify(state));let bin="";bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin).replaceAll("+","-").replaceAll("/","_").replace(/=+$/,"")}
function decode(value){let normalized=value.replaceAll("-","+").replaceAll("_","/");normalized+="=".repeat((4-normalized.length%4)%4);const bin=atob(normalized);const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return normalize(JSON.parse(new TextDecoder().decode(bytes)))}
function inviteUrl(){return location.origin+location.pathname+"#invite="+encode()}
async function copyText(text){if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(text);const area=document.createElement("textarea");area.value=text;area.style.position="fixed";area.style.opacity="0";document.body.append(area);area.select();document.execCommand("copy");area.remove()}
function directUrl(text){const contact=state.replyContact.trim();if(!contact)return"";if(state.replyChannel==="email")return`mailto:${encodeURIComponent(contact)}?subject=${encodeURIComponent("Ответ на DateQuest от "+state.to)}&body=${encodeURIComponent(text)}`;if(state.replyChannel==="telegram")return`https://t.me/${encodeURIComponent(contact.replace(/^@/,""))}`;const phone=contact.replace(/\D/g,"");return phone?`https://wa.me/${phone}?text=${encodeURIComponent(text)}`:""}
function finalFor(kind){const variants={yes:{symbol:"♥",title:"С радостью — звучит прекрасно.",copy:copy[state.theme].yes,reply:`${state.from}, да, с радостью 💛 Идея «${ideas[state.idea].title}» мне нравится. Хочу, чтобы вечер был ${feeling}, правило — ${token}, а ещё добавим ${extra}. Давай подтвердим детали!`},maybe:{symbol:"↝",title:"Давай найдём наш вариант.",copy:"Отличная идея не обязана совпасть с первой попытки. Предложи удобные время или место.",reply:`${state.from}, мне нравится приглашение, но давай подберём другой вариант по времени или месту 🙂`},no:{symbol:"○",title:"Спасибо за честный ответ.",copy:"Всё в порядке. Никаких объяснений не нужно — приглашение было без ожиданий и давления.",reply:`${state.from}, спасибо за красивое приглашение. Я не смогу, но ценю твоё внимание 💛`}}[kind];$("finalSymbol").textContent=variants.symbol;$("finalTitle").textContent=variants.title;$("finalCopy").textContent=variants.copy;$("replyText").textContent=variants.reply;const url=directUrl(variants.reply);$("sendDirect").href=url||"#";$("sendDirect").style.display=url?"inline-flex":"none";$("shareReply").textContent=url?"Другой мессенджер":"Отправить ответ ↗";setScene(8);if(kind==="yes")burst()}
function burst(){if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;const c=$("confetti"),ctx=c.getContext("2d"),ratio=devicePixelRatio||1;c.width=innerWidth*ratio;c.height=innerHeight*ratio;ctx.scale(ratio,ratio);const bits=Array.from({length:55},()=>({x:innerWidth/2,y:innerHeight*.55,vx:(Math.random()-.5)*10,vy:-4-Math.random()*7,g:.14+Math.random()*.08,r:3+Math.random()*5,color:["#ff86ad","#b997ff","#ffd19d","#fff8fc"][Math.floor(Math.random()*4)],life:90+Math.random()*35}));function frame(){ctx.clearRect(0,0,innerWidth,innerHeight);bits.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=p.g;p.life--;ctx.fillStyle=p.color;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.life*.08);ctx.fillRect(-p.r/2,-p.r,p.r,p.r*2);ctx.restore()});if(bits.some(p=>p.life>0))requestAnimationFrame(frame);else ctx.clearRect(0,0,innerWidth,innerHeight)}frame()}
function renderIdeaSelection(){document.querySelectorAll(".idea").forEach(b=>{const on=state.selectedIdeas.includes(b.dataset.idea);b.classList.toggle("active",on);b.setAttribute("aria-pressed",on)});const count=state.selectedIdeas.length,valid=count>=3&&count<=6;$("ideaCount").textContent=`Выбрано: ${count} из 6`;$("ideaValidation").textContent=count<3?`Добавь ещё ${3-count}`:"Можно продолжать";$("ideaCount").parentElement.classList.toggle("invalid",!valid)}
function selectIdea(key){const index=state.selectedIdeas.indexOf(key);if(index>=0){if(state.selectedIdeas.length>1)state.selectedIdeas.splice(index,1)}else if(state.selectedIdeas.length<6)state.selectedIdeas.push(key);renderIdeaSelection()}
function chooseMatchedPlan(exclude=""){const pool=state.selectedIdeas.filter(key=>key!==exclude);let ranked=pool.map((key,index)=>({key,index,score:(ideaTags[key]||[]).includes(feeling)*3+(ideaTags[key]||[]).includes(token)*2})).sort((a,b)=>b.score-a.score||a.index-b.index);const winner=ranked[0]||{key:"coffee",score:0};state.idea=winner.key;const idea=ideas[state.idea];$("ideaTitle").textContent=idea.title;$("ideaIcon").textContent=idea.icon;$("ideaDescription").textContent=idea.description;$("matchReason").textContent=`Подходит под карты «${feeling}» и «${token}» · выбран из ${state.selectedIdeas.length} вариантов автора`;const card=$("ideaTitle").closest(".scene").querySelector(".route-card");card.classList.remove("reveal");requestAnimationFrame(()=>card.classList.add("reveal"))}
function loadInvite(){if(!location.hash.startsWith("#invite="))return false;try{Object.assign(state,decode(location.hash.slice(8)));["from","to","openingText","openingNote","message","place","date","dateFrom","dateTo","replyChannel","replyContact"].forEach(k=>$(k).value=state[k]);document.querySelectorAll(".theme").forEach(b=>{const on=b.dataset.theme===state.theme;b.classList.toggle("active",on);b.setAttribute("aria-pressed",on)});renderIdeaSelection();document.body.classList.add("invite-mode");sync();setScene(0);return true}catch{$("builderStatus").textContent="Ссылка повреждена. Можно создать новое приглашение.";return false}}
$("randomMood").addEventListener("click",()=>{const cards=[...document.querySelectorAll("[data-feel]")],card=cards[Math.floor(Math.random()*cards.length)];card.click()});$("guestDate").addEventListener("input",()=>$("confirmDate").disabled=!$("guestDate").value);$("confirmDate").addEventListener("click",()=>{guestDate=$("guestDate").value;setScene(7)});document.querySelectorAll("[data-copy]").forEach(b=>b.addEventListener("click",()=>{$("message").value=b.dataset.copy.replace("{name}",$("to").value||"Имя");sync()}));document.querySelectorAll("[data-next]").forEach(b=>b.addEventListener("click",()=>setScene(scene+1)));document.querySelectorAll("[data-decline]").forEach(b=>b.addEventListener("click",()=>finalFor("no")));document.querySelectorAll("[data-feel]").forEach(b=>b.addEventListener("click",()=>{feeling=b.dataset.feel;document.querySelectorAll("[data-feel]").forEach(card=>card.classList.toggle("selected",card===b));$("boardResult").textContent=`Карта выбрана: ${b.querySelector("span").childNodes[0].textContent.trim()} ✦`;setTimeout(()=>setScene(2),450)}));document.querySelectorAll("[data-token]").forEach(b=>b.addEventListener("click",()=>{token=b.dataset.token;chooseMatchedPlan();setScene(3)}));document.querySelectorAll("[data-extra]").forEach(b=>b.addEventListener("click",()=>{extra=b.dataset.extra;setScene(6)}));document.querySelectorAll("[data-answer]").forEach(b=>b.addEventListener("click",()=>finalFor(b.dataset.answer)));document.querySelectorAll("[data-idea]").forEach(b=>b.addEventListener("click",()=>selectIdea(b.dataset.idea)));$("rerollPlan").addEventListener("click",()=>chooseMatchedPlan(state.idea));document.querySelectorAll(".theme").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".theme").forEach(x=>{x.classList.toggle("active",x===b);x.setAttribute("aria-pressed",x===b)});state.theme=b.dataset.theme;$("openingText").value=copy[state.theme].intro;state.openingText=copy[state.theme].intro;sync();setScene(0)}));["from","to","openingText","openingNote","message","place","date","dateFrom","dateTo","replyChannel","replyContact"].forEach(id=>$(id).addEventListener("input",sync));
$("restart").addEventListener("click",()=>setScene(0));$("demo").addEventListener("click",()=>{$("studio").scrollIntoView();setScene(0)});$("copy").addEventListener("click",async()=>{read();if(state.replyContact&&state.replyChannel==="email"&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(state.replyContact)){$("builderStatus").textContent="Проверь email для получения ответа.";return}try{await copyText(inviteUrl());$("builderStatus").textContent=state.replyContact?"Ссылка скопирована. Ответ придёт в выбранный канал ✦":"Ссылка скопирована. Добавь контакт, если хочешь получить ответ напрямую."}catch{$("builderStatus").textContent="Не получилось скопировать — скопируй адрес страницы вручную."}});$("shareReply").addEventListener("click",async()=>{const text=$("replyText").textContent;if(navigator.share){try{await navigator.share({title:"Мой ответ на DateQuest",text});return}catch(e){if(e.name==="AbortError")return}}await copyText(text);$("shareReply").textContent="Ответ скопирован ✓"});$("sendDirect").addEventListener("click",async()=>{if(state.replyChannel==="telegram")await copyText($("replyText").textContent)});$("copyReply").addEventListener("click",async()=>{await copyText($("replyText").textContent);$("copyReply").textContent="Скопировано ✓"});
let builderStep=1;function setBuilderStep(step){builderStep=Math.max(1,Math.min(4,step));document.querySelectorAll("[data-builder-panel]").forEach(panel=>panel.classList.toggle("active",Number(panel.dataset.builderPanel)===builderStep));document.querySelectorAll("[data-builder-step]").forEach(button=>button.classList.toggle("active",Number(button.dataset.builderStep)===builderStep));$("builderStepLabel").textContent=`Шаг ${builderStep} из 4`;$("builderPrev").style.visibility=builderStep===1?"hidden":"visible";$("builderPrev").disabled=builderStep===1;$("builderNext").style.visibility=builderStep===4?"hidden":"visible";$("builderNext").textContent=builderStep===3?"К финалу →":"Дальше →"}document.querySelectorAll("[data-builder-step]").forEach(button=>button.addEventListener("click",()=>setBuilderStep(Number(button.dataset.builderStep))));$("builderPrev").addEventListener("click",()=>setBuilderStep(builderStep-1));$("builderNext").addEventListener("click",()=>setBuilderStep(builderStep+1));$("coverPhoto").addEventListener("change",event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader(),image=new Image();reader.onload=()=>image.src=reader.result;image.onload=()=>{const canvas=document.createElement("canvas"),scale=Math.min(1,420/Math.max(image.width,image.height));canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);state.coverPhoto=canvas.toDataURL("image/jpeg",.55);$("coverPreview").src=state.coverPhoto;$("coverFallback").style.display="none";$("builderStatus").textContent="Фото добавлено на конверт ✦"};reader.readAsDataURL(file)});setBuilderStep(1);const dialog=$("privacyDialog");["privacyOpen","privacyFooter"].forEach(id=>$(id).addEventListener("click",()=>dialog.showModal()));["privacyClose","privacyDone"].forEach(id=>$(id).addEventListener("click",()=>dialog.close()));dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});sync();renderIdeaSelection();loadInvite();
