const $=id=>document.getElementById(id);
const defaults={from:"Маша",to:"Саша",theme:"tender",message:"Мне хорошо с тобой, и я хочу провести вместе ещё один красивый вечер.",place:"кофейня с видом на город",date:"",clue:"coffee"};
const allowed={theme:["tender","playful","mystery"],clue:["coffee","city","cinema","surprise"]};
const state={...defaults};let scene=0,feeling="уютно",answer="yes";
const copy={tender:{intro:"у меня для тебя маленькое послание.",yes:"Мне очень приятно. Кажется, впереди хороший вечер ✦"},playful:{intro:"похоже, нас ждёт маленькая авантюра.",yes:"Вот это поворот. Приключение официально начинается ✦"},mystery:{intro:"для тебя оставили послание из будущего.",yes:"Будущее стало немного яснее. До встречи под звёздами ✦"}};
const clueIcons={coffee:"☕",city:"✦",cinema:"◐",surprise:"?"};
function safeText(value,max,fallback=""){return typeof value==="string"?value.trim().slice(0,max)||fallback:fallback}
function normalize(raw={}){return{from:safeText(raw.from,40,defaults.from),to:safeText(raw.to,40,defaults.to),theme:allowed.theme.includes(raw.theme)?raw.theme:defaults.theme,message:safeText(raw.message,280,defaults.message),place:safeText(raw.place,80,defaults.place),date:/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(raw.date||"")?raw.date:"",clue:allowed.clue.includes(raw.clue)?raw.clue:defaults.clue}}
function read(){["from","to","message","place","date","clue"].forEach(k=>state[k]=$(k).value);return Object.assign(state,normalize(state))}
function fmt(value){if(!value)return"время выберем вместе";const date=new Date(value);return Number.isNaN(date.valueOf())?"время уточним":new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"long",hour:"2-digit",minute:"2-digit"}).format(date)}
function sync(){read();document.body.dataset.theme=state.theme;$("introFrom").textContent=state.from;$("introTitle").textContent=(state.to||"Тебе")+", "+copy[state.theme].intro;$("letterTo").textContent=(state.to||"Тебе")+", это для тебя";$("letterText").textContent=state.message;$("placePill").textContent="⌖ "+state.place;$("datePill").textContent="◷ "+fmt(state.date);$("clueIcon").textContent=clueIcons[state.clue];$("messageCount").textContent=$("message").value.length;$("replyTo").textContent=state.from}
function setScene(n){scene=Math.max(0,Math.min(4,n));document.querySelectorAll(".scene").forEach((el,i)=>{el.classList.toggle("active",i===scene);el.classList.toggle("exit",i<scene)});document.querySelectorAll(".progress i").forEach((el,i)=>el.classList.toggle("on",i<=Math.min(scene,3)));$("stepText").textContent=Math.min(scene+1,4)+" / 4"}
function encode(){read();const bytes=new TextEncoder().encode(JSON.stringify(state));let bin="";bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin).replaceAll("+","-").replaceAll("/","_").replace(/=+$/,"")}
function decode(value){const normalized=value.replaceAll("-","+").replaceAll("_","/");const bin=atob(normalized);const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return normalize(JSON.parse(new TextDecoder().decode(bytes)))}
function inviteUrl(){return location.origin+location.pathname+"#invite="+encode()}
async function copyText(text){if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(text);const area=document.createElement("textarea");area.value=text;area.style.position="fixed";area.style.opacity="0";document.body.append(area);area.select();document.execCommand("copy");area.remove()}
function finalFor(kind){answer=kind;const variants={yes:{symbol:"♥",title:"С радостью — звучит прекрасно.",copy:copy[state.theme].yes,reply:`Да, с радостью 💛 Вайб — ${feeling}. Давай подтвердим детали!`},maybe:{symbol:"↝",title:"Давай найдём наш вариант.",copy:"Отличная идея не обязана совпасть с первой попытки. Предложи удобные время или место.",reply:"Мне нравится идея, но давай подберём другой вариант по времени или месту 🙂"},no:{symbol:"○",title:"Спасибо за честный ответ.",copy:"Всё в порядке. Никаких объяснений не нужно — приглашение было без ожиданий и давления.",reply:"Спасибо за красивое приглашение. Я не смогу, но ценю твоё внимание 💛"}}[kind];$("finalSymbol").textContent=variants.symbol;$("finalTitle").textContent=variants.title;$("finalCopy").textContent=variants.copy;$("replyText").textContent=variants.reply;setScene(4);if(kind==="yes")burst()}
function burst(){if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;const c=$("confetti"),ctx=c.getContext("2d"),ratio=devicePixelRatio||1;c.width=innerWidth*ratio;c.height=innerHeight*ratio;ctx.scale(ratio,ratio);const bits=Array.from({length:55},()=>({x:innerWidth/2,y:innerHeight*.55,vx:(Math.random()-.5)*10,vy:-4-Math.random()*7,g:.14+Math.random()*.08,r:3+Math.random()*5,color:["#ff86ad","#b997ff","#ffd19d","#fff8fc"][Math.floor(Math.random()*4)],life:90+Math.random()*35}));function frame(){ctx.clearRect(0,0,innerWidth,innerHeight);bits.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=p.g;p.life--;ctx.fillStyle=p.color;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.life*.08);ctx.fillRect(-p.r/2,-p.r,p.r,p.r*2);ctx.restore()});if(bits.some(p=>p.life>0))requestAnimationFrame(frame);else ctx.clearRect(0,0,innerWidth,innerHeight)}frame()}
function loadInvite(){if(!location.hash.startsWith("#invite="))return false;try{Object.assign(state,decode(location.hash.slice(8)));["from","to","message","place","date","clue"].forEach(k=>$(k).value=state[k]);document.querySelectorAll(".theme").forEach(b=>{const on=b.dataset.theme===state.theme;b.classList.toggle("active",on);b.setAttribute("aria-pressed",on)});document.body.classList.add("invite-mode");sync();setScene(0);return true}catch{$("builderStatus").textContent="Ссылка повреждена. Можно создать новое приглашение.";return false}}
document.querySelectorAll("[data-next]").forEach(b=>b.addEventListener("click",()=>setScene(scene+1)));document.querySelectorAll("[data-decline]").forEach(b=>b.addEventListener("click",()=>finalFor("no")));document.querySelectorAll("[data-feel]").forEach(b=>b.addEventListener("click",()=>{feeling=b.dataset.feel;setScene(2)}));document.querySelectorAll("[data-answer]").forEach(b=>b.addEventListener("click",()=>finalFor(b.dataset.answer)));document.querySelectorAll(".theme").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".theme").forEach(x=>{x.classList.toggle("active",x===b);x.setAttribute("aria-pressed",x===b)});state.theme=b.dataset.theme;sync();setScene(0)}));["from","to","message","place","date","clue"].forEach(id=>$(id).addEventListener("input",sync));
$("restart").addEventListener("click",()=>setScene(0));$("demo").addEventListener("click",()=>{$("studio").scrollIntoView();setScene(0)});$("copy").addEventListener("click",async()=>{try{await copyText(inviteUrl());$("builderStatus").textContent="Ссылка скопирована. Маленькое приключение готово ✦"}catch{$("builderStatus").textContent="Не получилось скопировать — скопируй адрес страницы вручную."}});$("shareReply").addEventListener("click",async()=>{const text=$("replyText").textContent;if(navigator.share){try{await navigator.share({title:"Мой ответ на DateQuest",text});return}catch(e){if(e.name==="AbortError")return}}await copyText(text);$("shareReply").textContent="Ответ скопирован ✓"});$("copyReply").addEventListener("click",async()=>{await copyText($("replyText").textContent);$("copyReply").textContent="Скопировано ✓"});
const dialog=$("privacyDialog");["privacyOpen","privacyFooter"].forEach(id=>$(id).addEventListener("click",()=>dialog.showModal()));["privacyClose","privacyDone"].forEach(id=>$(id).addEventListener("click",()=>dialog.close()));dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});sync();loadInvite();
